
import { UnitType, Unit } from './types';

export const UNIT_PRICES: Record<UnitType, { tier: number, cost: number }> = {
  [UnitType.PYRUS]: { tier: 1, cost: 0 },
  [UnitType.AEGIS]: { tier: 1, cost: 200 },
  [UnitType.GHOST]: { tier: 2, cost: 500 },
  [UnitType.REAPER]: { tier: 2, cost: 600 },
  [UnitType.HUNTER]: { tier: 3, cost: 750 }, // Swapped with Medic
  [UnitType.MEDIC]: { tier: 3, cost: 800 }, // Medic is more valuable due to Purify
};

export const UNITS: Record<UnitType, Unit> = {
  [UnitType.PYRUS]: {
    type: UnitType.PYRUS,
    name: 'PYRUS',
    role: 'Baseline',
    description: 'The control group. Balanced at all ranges.',
    special: 'Firewall: 100 DMG + chance to Drain AP.',
    hp: 1000,
    maxHp: 1000,
    speed: 1.0,
    focus: 0.2,
    range: 4,
    atkStat: 1.0,
    defStat: 1.0,
    passiveDesc: 'Cinder: 20% chance to inflict Burn (50 dmg/round).',
    activeDesc: 'Firewall: CD 3. 100 DMG + 50% chance to Drain 1 AP.',
    desperationName: 'Solar Flare',
    desperationDesc: 'Deals 5x Damage (500) to ALL enemies. No range limit.',
    cooldownMax: 3,
    truth: 'Logic is flammable.',
    image: 'assets/Pyrus.webp'
  },
  [UnitType.AEGIS]: {
    type: UnitType.AEGIS,
    name: 'AEGIS',
    role: 'Tank',
    description: 'Punishes Aggro players. Forces enemies to use AP to flank.',
    special: 'Titan Shield: 80% DR for 1 round.',
    hp: 1400,
    maxHp: 1400,
    speed: 0.6,
    focus: 0.05,
    range: 2,
    atkStat: 0.8,
    defStat: 1.5,
    passiveDesc: 'Inertia: Cannot be displaced by collision/knockback. +15% Shield Efficiency.',
    activeDesc: 'Titan Shield: Once per game. 80% Damage Reduction for 1 round.',
    desperationName: 'Iron Dome',
    desperationDesc: 'Become IMMOVABLE for 2 turns. 90% DMG Reduction. Cannot Capture objectives while active.',
    cooldownMax: -1,
    truth: 'Steel is stronger than ego.',
    image: 'assets/Aegis.webp'
  },
  [UnitType.GHOST]: {
    type: UnitType.GHOST,
    name: 'GHOST',
    role: 'Speed',
    description: 'The Initiative King. Wins the Snap but dies to a stiff breeze.',
    special: 'Phase Shift: Untargetable for 1 round.',
    hp: 700,
    maxHp: 700,
    speed: 1.6,
    focus: 0.35,
    range: 4,
    atkStat: 1.2,
    defStat: 0.6,
    passiveDesc: 'Phase Shift (Untargetable when active)',
    activeDesc: 'Phase Shift: CD 4. Untargetable this round. Cannot Attack.',
    desperationName: 'Phantom Step',
    desperationDesc: 'Immediate Phase Shift. Recover 300 HP and relocate to start position.',
    cooldownMax: 4,
    truth: 'You cannot kill what isn\'t there.',
    image: './assets/Ghost.webp',
    minTierToPierceWalls: 3
  },
  [UnitType.REAPER]: {
    type: UnitType.REAPER,
    name: 'REAPER',
    role: 'Sniper',
    description: 'Controls the map. Range 7. Slow, so it must be protected.',
    special: 'Marked for Death: Reveals target + Vuln.',
    hp: 900,
    maxHp: 900,
    speed: 0.9,
    focus: 0.45,
    range: 7,
    atkStat: 1.4,
    defStat: 0.7,
    passiveDesc: 'Final Blow: Always wins initiative in mutual kills.',
    activeDesc: 'Marked for Death: CD 3. Target cannot hide in Fog. Takes +30% DMG.',
    desperationName: 'Final Harvest',
    desperationDesc: 'If target < 30% HP, instant EXECUTE. Otherwise 6.0x Damage.',
    cooldownMax: 3,
    truth: 'The harvest comes for all.',
    image: 'assets/Reaper.webp'
  },
  [UnitType.HUNTER]: {
    type: UnitType.HUNTER,
    name: 'HUNTER',
    role: 'Chaser',
    description: 'High Speed, average Atk. Designed to hunt the Ghost.',
    special: 'Target Lock: Permanent +30% damage to mark.',
    hp: 1100,
    maxHp: 1100,
    speed: 1.3,
    focus: 0.25,
    range: 2,
    atkStat: 1.0,
    defStat: 0.9,
    passiveDesc: 'Eagle Eye: Ignores the -15% Damage Penalty for Far Range (3+ tiles).',
    activeDesc: 'Target Lock: Permanent +30% damage to marked target.',
    desperationName: 'Apex Predator',
    desperationDesc: 'Your next attack fires 3 times at full damage.',
    cooldownMax: -1,
    truth: 'Running only makes the trail easier to follow.',
    image: 'assets/Hunter.webp'
  },
  [UnitType.MEDIC]: {
    type: UnitType.MEDIC,
    name: 'MEDIC',
    role: 'Sustain',
    description: 'Converts AP into longevity. Punishes low-damage teams.',
    special: 'Emergency Patch: Restore 400 HP.',
    hp: 1200,
    maxHp: 1200,
    speed: 0.8,
    focus: 0.15,
    range: 4,
    atkStat: 0.6,
    defStat: 1.2,
    passiveDesc: 'Purify: Immune to Status Effects (Toxic, Burn, etc).',
    activeDesc: 'Emergency Patch: Once per game. Heal 400 HP.',
    desperationName: 'Bio-Surge',
    desperationDesc: 'Heal 300 HP immediately. Remove all negative status effects.',
    cooldownMax: -1,
    truth: 'I fix the code; you fix the target.',
    image: 'assets/Medic.webp'
  }
};
