
import { UnitType, Unit } from './types';

export const UNIT_PRICES: Record<UnitType, { tier: number, cost: number }> = {
  [UnitType.GHOST]: { tier: 1, cost: 0 },
  [UnitType.AEGIS]: { tier: 1, cost: 0 },
  [UnitType.REAPER]: { tier: 1, cost: 500 },
  [UnitType.PYRUS]: { tier: 1, cost: 450 },
  [UnitType.TROJAN]: { tier: 2, cost: 600 },
  [UnitType.KILLSHOT]: { tier: 2, cost: 750 },
  [UnitType.HUNTER]: { tier: 2, cost: 400 },
  [UnitType.PYTHON]: { tier: 2, cost: 550 },
  [UnitType.MEDIC]: { tier: 2, cost: 500 },
  [UnitType.BATTERY]: { tier: 2, cost: 700 },
  [UnitType.RAVEN]: { tier: 3, cost: 1000 },
  [UnitType.LEECH]: { tier: 3, cost: 800 },
  [UnitType.STATIC]: { tier: 3, cost: 850 },
};

export const UNITS: Record<UnitType, Unit> = {
  [UnitType.GHOST]: {
    type: UnitType.GHOST,
    name: 'GHOST',
    role: 'Survivalist',
    description: 'Master of evasion and energy preservation.',
    special: 'Phase Shift: Untargetable for 1 round.',
    hp: 900,
    maxHp: 900,
    speed: 8,
    focus: 0,
    passiveDesc: 'Phase Shift (Untargetable when active)',
    activeDesc: 'Phase Shift: CD 4. Untargetable this round. Cannot Attack, only Move or Reserve.',
    cooldownMax: 4,
    truth: 'You cannot kill what isn\'t there.',
  },
  [UnitType.AEGIS]: {
    type: UnitType.AEGIS,
    name: 'AEGIS',
    role: 'Tank',
    description: 'The immovable object of the tactical grid.',
    special: 'Titan Shield: 80% DR for 1 round.',
    hp: 1200,
    maxHp: 1200,
    speed: 3,
    focus: 0,
    passiveDesc: 'Hardened: Flat 10% Damage Reduction (DR).',
    activeDesc: 'Titan Shield: Once per game. 80% Damage Reduction for 1 round.',
    cooldownMax: -1,
    truth: 'Steel is stronger than ego.',
  },
  [UnitType.REAPER]: {
    type: UnitType.REAPER,
    name: 'REAPER',
    role: 'Executioner',
    description: 'The inevitable end of every cycle.',
    special: 'Final Harvest: Execute targets < 25% HP.',
    hp: 1000,
    maxHp: 1000,
    speed: 9,
    focus: 0,
    passiveDesc: 'Final Blow: Always wins initiative in mutual kills.',
    activeDesc: 'Final Harvest: Once per game. Execution if target < 250 HP (25%).',
    cooldownMax: -1,
    truth: 'The harvest comes for all.',
  },
  [UnitType.PYRUS]: {
    type: UnitType.PYRUS,
    name: 'PYRUS',
    role: 'Aggressor',
    description: 'Burn the system to the ground.',
    special: 'Firewall: 100 DMG + chance to Drain AP.',
    hp: 1000,
    maxHp: 1000,
    speed: 6,
    focus: 0,
    passiveDesc: 'Cinder: 20% chance to inflict Burn (50 dmg/round for 2 turns).',
    activeDesc: 'Firewall: CD 3. 100 DMG + 50% chance to Drain 1 AP.',
    cooldownMax: 3,
    truth: 'Logic is flammable.',
  },
  [UnitType.TROJAN]: {
    type: UnitType.TROJAN,
    name: 'TROJAN',
    role: 'Specialist',
    description: 'Bypasses the strongest defenses.',
    special: 'Overclock: Ignore all Defense for next 3 points.',
    hp: 1000,
    maxHp: 1000,
    speed: 7,
    focus: 0,
    passiveDesc: 'Null-Reflect: Immune to Reflect. 15% Shield Pierce chance.',
    activeDesc: 'Overclock: Once per game. Next 3 attack points ignore all Defense.',
    cooldownMax: -1,
    truth: 'Every wall has a back door.',
  },
  [UnitType.KILLSHOT]: {
    type: UnitType.KILLSHOT,
    name: 'KILLSHOT',
    role: 'Sniper',
    description: 'High lethality, low sustainability.',
    special: 'Double Tap: 2 Free Basic Attacks.',
    hp: 900,
    maxHp: 900,
    speed: 10,
    focus: 10,
    passiveDesc: 'Lethality: 10% Base Damage increase.',
    activeDesc: 'Double Tap: CD 5. 2 Free Basic Attacks (0 AP).',
    cooldownMax: 5,
    truth: 'One shot. One simulation.',
  },
  [UnitType.HUNTER]: {
    type: UnitType.HUNTER,
    name: 'HUNTER',
    role: 'Scout',
    description: 'Tracks and eliminates priority assets.',
    special: 'Target Lock: Permanent +30% damage to mark.',
    hp: 1050,
    maxHp: 1050,
    speed: 5,
    focus: 25,
    passiveDesc: 'Eagle Eye: 25 Focus. Ignores distance penalties.',
    activeDesc: 'Target Lock: Permanent +30% damage to marked target.',
    cooldownMax: -1,
    truth: 'Running only makes the trail easier to follow.',
  },
  [UnitType.PYTHON]: {
    type: UnitType.PYTHON,
    name: 'PYTHON',
    role: 'Controller',
    description: 'Slow, agonizing systems failure.',
    special: 'Neural Paralysis: Disable enemy Reserve AP.',
    hp: 950,
    maxHp: 950,
    speed: 4,
    focus: 0,
    passiveDesc: 'Toxin: 35% Poison chance (40 dmg + target deals 20% less dmg).',
    activeDesc: 'Neural Paralysis: Once per game. Target cannot Reserve AP next turn.',
    cooldownMax: -1,
    truth: 'The tightest grip is the one you don\'t feel.',
  },
  [UnitType.MEDIC]: {
    type: UnitType.MEDIC,
    name: 'MEDIC',
    role: 'Support',
    description: 'Neural integrity is the only priority.',
    special: 'Emergency Patch: Restore 40% HP.',
    hp: 1100,
    maxHp: 1100,
    speed: 2,
    focus: 0,
    passiveDesc: 'Purify: Immune to Status Effects (Burn, Poison, Paralyze).',
    activeDesc: 'Emergency Patch: Once per game. Heal 400 HP (40%).',
    cooldownMax: -1,
    truth: 'I can fix the code, but I can\'t fix your aim.',
  },
  [UnitType.LEECH]: {
    type: UnitType.LEECH,
    name: 'LEECH',
    role: 'Parasite',
    description: 'Thrives on the life force of others.',
    special: 'Siphon Soul: 100% Lifesteal for 1 round.',
    hp: 900,
    maxHp: 900,
    speed: 5,
    focus: 0,
    passiveDesc: 'Vampiric Link: Heals for 30% of unshielded damage.',
    activeDesc: 'Siphon Soul: Once per game. 100% Lifesteal for 1 round.',
    cooldownMax: -1,
    truth: 'Your strength is my fuel.',
  },
  [UnitType.BATTERY]: {
    type: UnitType.BATTERY,
    name: 'BATTERY',
    role: 'Overcharger',
    description: 'Converts pain into tactical momentum.',
    special: 'Overcharge: Instantly gain +4 AP.',
    hp: 1000,
    maxHp: 1000,
    speed: 4,
    focus: 0,
    passiveDesc: 'Kinetic Storage: Gain +1 AP when damaged (Max +2).',
    activeDesc: 'Overcharge: Once per game. +4 AP now, but lose 100 HP.',
    cooldownMax: -1,
    truth: 'Burning twice as bright for half as long.',
  },
  [UnitType.STATIC]: {
    type: UnitType.STATIC,
    name: 'STATIC',
    role: 'Disruptor',
    description: 'Punishes the aggressive and the greedy alike.',
    special: 'Blackout Pulse: Cap enemy AP pool.',
    hp: 1000,
    maxHp: 1000,
    speed: 7,
    focus: 0,
    passiveDesc: 'Feedback Loop: Enemies take 50 dmg per extra AP gained.',
    activeDesc: 'Blackout Pulse: CD 5. Reduce enemy Base AP to 2 for next round.',
    cooldownMax: 5,
    truth: 'Silence is the best strategy.',
  },
  [UnitType.RAVEN]: {
    type: UnitType.RAVEN,
    name: 'RAVEN',
    role: 'Intel',
    description: 'Sees the future before it happens.',
    special: 'Precog: View and override opponent actions.',
    hp: 850,
    maxHp: 850,
    speed: 6,
    focus: 0,
    passiveDesc: 'Insight: Sees enemy Class and current HP.',
    activeDesc: 'Precog: Once per game. View opponent choices and change one action.',
    cooldownMax: -1,
    truth: 'Knowledge is the only real weapon.',
  }
};
