
import { UnitType, Unit } from './types';

export const UNIT_PRICES: Record<UnitType, { tier: number, cost: number }> = {
  [UnitType.GHOST]: { tier: 1, cost: 0 },
  [UnitType.AEGIS]: { tier: 1, cost: 100 }, // Updated cost
  [UnitType.REAPER]: { tier: 1, cost: 500 },
  [UnitType.PYRUS]: { tier: 1, cost: 450 },
  [UnitType.TROJAN]: { tier: 2, cost: 600 },
  [UnitType.KILLSHOT]: { tier: 2, cost: 750 },
  [UnitType.HUNTER]: { tier: 2, cost: 400 },
  [UnitType.PYTHON]: { tier: 2, cost: 550 },
  [UnitType.MEDIC]: { tier: 2, cost: 500 },
  [UnitType.BATTERY]: { tier: 2, cost: 700 },
  [UnitType.GLITCH]: { tier: 2, cost: 650 },
  [UnitType.WARDEN]: { tier: 3, cost: 900 },
  [UnitType.LEECH]: { tier: 3, cost: 800 },
  [UnitType.STATIC]: { tier: 3, cost: 850 },
  [UnitType.RAVEN]: { tier: 3, cost: 1000 },
  [UnitType.SINGULARITY]: { tier: 3, cost: 5000 },
};

export const UNITS: Record<UnitType, Unit> = {
  [UnitType.GHOST]: {
    type: UnitType.GHOST,
    name: 'GHOST',
    role: 'Evasive',
    description: 'Avoids hits via Phase Shift. Low damage, high survival.',
    special: 'Phase Shift: Untargetable for 1 round.',
    hp: 800,
    maxHp: 800,
    speed: 8,
    focus: 0,
    dmgMultiplier: 0.9,
    passiveDesc: 'Phase Shift (Untargetable when active)',
    activeDesc: 'Phase Shift: CD 4. Untargetable this round. Cannot Attack.',
    cooldownMax: 4,
    truth: 'You cannot kill what isn\'t there.',
  },
  [UnitType.AEGIS]: {
    type: UnitType.AEGIS,
    name: 'AEGIS',
    role: 'Tank',
    description: 'Near-impossible to crack. Slow to strike, massive defense.',
    special: 'Titan Shield: 80% DR for 1 round.',
    hp: 1200,
    maxHp: 1200,
    speed: 2,
    focus: 0,
    dmgMultiplier: 0.8,
    passiveDesc: 'Hardened: Flat 10% Damage Reduction (DR).',
    activeDesc: 'Titan Shield: Once per game. 80% Damage Reduction for 1 round.',
    cooldownMax: -1,
    truth: 'Steel is stronger than ego.',
  },
  [UnitType.REAPER]: {
    type: UnitType.REAPER,
    name: 'REAPER',
    role: 'Executioner',
    description: 'High speed, low mercy. Executes the weak.',
    special: 'Final Harvest: Execute targets < 25% HP.',
    hp: 1000,
    maxHp: 1000,
    speed: 9,
    focus: 0,
    dmgMultiplier: 1.0,
    passiveDesc: 'Final Blow: Always wins initiative in mutual kills.',
    activeDesc: 'Final Harvest: Once per game. Execute if target < 250 HP.',
    cooldownMax: -1,
    truth: 'The harvest comes for all.',
  },
  [UnitType.PYRUS]: {
    type: UnitType.PYRUS,
    name: 'PYRUS',
    role: 'Bruiser',
    description: 'High pressure aggressor. Deals intense Burn damage.',
    special: 'Firewall: 100 DMG + chance to Drain AP.',
    hp: 900,
    maxHp: 900,
    speed: 5,
    focus: 0,
    dmgMultiplier: 1.2,
    passiveDesc: 'Cinder: 20% chance to inflict Burn (50 dmg/round).',
    activeDesc: 'Firewall: CD 3. 100 DMG + 50% chance to Drain 1 AP.',
    cooldownMax: 3,
    truth: 'Logic is flammable.',
  },
  [UnitType.TROJAN]: {
    type: UnitType.TROJAN,
    name: 'TROJAN',
    role: 'Hacker',
    description: 'Balanced specialist. Relies on Overclocking for high-burst.',
    special: 'Overclock: Next 3 attack points ignore all Defense.',
    hp: 900,
    maxHp: 900,
    speed: 6,
    focus: 0,
    dmgMultiplier: 1.0,
    passiveDesc: 'Null-Reflect: Immune to Reflect. 15% Shield Pierce chance.',
    activeDesc: 'Overclock: Once per game. 3 points of Shield Pierce.',
    cooldownMax: -1,
    truth: 'Every wall has a back door.',
  },
  [UnitType.KILLSHOT]: {
    type: UnitType.KILLSHOT,
    name: 'KILLSHOT',
    role: 'Glass Cannon',
    description: 'Always goes first; kills fast or dies fast.',
    special: 'Double Tap: 2 Free Basic Attacks.',
    hp: 700,
    maxHp: 700,
    speed: 9,
    focus: 10,
    dmgMultiplier: 1.4,
    passiveDesc: 'Lethality: 10% Base Damage increase.',
    activeDesc: 'Double Tap: CD 5. 2 Free Basic Attacks (0 AP).',
    cooldownMax: 5,
    truth: 'One shot. One simulation.',
  },
  [UnitType.HUNTER]: {
    type: UnitType.HUNTER,
    name: 'HUNTER',
    role: 'Sniper',
    description: 'Lethal at range; weak in close engagement.',
    special: 'Target Lock: Permanent +30% damage to mark.',
    hp: 850,
    maxHp: 850,
    speed: 7,
    focus: 25,
    dmgMultiplier: 1.1,
    passiveDesc: 'Eagle Eye: Ignores distance penalties at Far range.',
    activeDesc: 'Target Lock: Permanent +30% damage to marked target.',
    cooldownMax: -1,
    truth: 'Running only makes the trail easier to follow.',
  },
  [UnitType.PYTHON]: {
    type: UnitType.PYTHON,
    name: 'PYTHON',
    role: 'Controller',
    description: 'Slow systems failure. Constricts enemy energy.',
    special: 'Neural Paralysis: Disable enemy Reserve AP.',
    hp: 950,
    maxHp: 950,
    speed: 4,
    focus: 0,
    dmgMultiplier: 0.9,
    passiveDesc: 'Toxin: 35% Poison chance.',
    activeDesc: 'Neural Paralysis: Once per game. Target cannot Reserve AP.',
    cooldownMax: -1,
    truth: 'The tightest grip is the one you don\'t feel.',
  },
  [UnitType.MEDIC]: {
    type: UnitType.MEDIC,
    name: 'MEDIC',
    role: 'Support',
    description: 'Neural integrity specialist. The system\'s fail-safe.',
    special: 'Emergency Patch: Restore 400 HP.',
    hp: 1100,
    maxHp: 1100,
    speed: 2,
    focus: 0,
    dmgMultiplier: 0.8,
    passiveDesc: 'Purify: Immune to Status Effects.',
    activeDesc: 'Emergency Patch: Once per game. Heal 400 HP.',
    cooldownMax: -1,
    truth: 'I fix the code; you fix the target.',
  },
  [UnitType.LEECH]: {
    type: UnitType.LEECH,
    name: 'LEECH',
    role: 'Sustain',
    description: 'Thrives on energy theft. Heals on impact.',
    special: 'Siphon Soul: 100% Lifesteal for 1 round.',
    hp: 1000,
    maxHp: 1000,
    speed: 4,
    focus: 0,
    dmgMultiplier: 1.0,
    passiveDesc: 'Vampiric Link: Passive 30% Lifesteal.',
    activeDesc: 'Siphon Soul: Once per game. 100% Lifesteal this round.',
    cooldownMax: -1,
    truth: 'Your strength is my fuel.',
  },
  [UnitType.BATTERY]: {
    type: UnitType.BATTERY,
    name: 'BATTERY',
    role: 'Overcharger',
    description: 'Converts pain into tactical momentum.',
    special: 'Overcharge: Instantly gain +4 AP.',
    hp: 1000,
    maxHp: 1000,
    speed: 4,
    focus: 0,
    dmgMultiplier: 0.9,
    passiveDesc: 'Kinetic Storage: Gain AP when damaged.',
    activeDesc: 'Overcharge: Once per game. +4 AP, -100 HP.',
    cooldownMax: -1,
    truth: 'Burning twice as bright for half as long.',
  },
  [UnitType.STATIC]: {
    type: UnitType.STATIC,
    name: 'STATIC',
    role: 'Disruptor',
    description: 'Punishes energy greed. Caps enemy potential.',
    special: 'Blackout Pulse: Cap enemy AP pool.',
    hp: 1000,
    maxHp: 1000,
    speed: 7,
    focus: 0,
    dmgMultiplier: 0.8,
    passiveDesc: 'Feedback Loop: Damage enemies for extra AP gained.',
    activeDesc: 'Blackout Pulse: CD 5. Reduce enemy Base AP to 2.',
    cooldownMax: 5,
    truth: 'Silence is the best strategy.',
  },
  [UnitType.GLITCH]: {
    type: UnitType.GLITCH,
    name: 'GLITCH',
    role: 'Disruptor',
    description: 'Fastest unit. Utility-focused, low direct damage.',
    special: 'Jitter: Randomly force target to Move or Reserve.',
    hp: 750,
    maxHp: 750,
    speed: 10,
    focus: 0,
    dmgMultiplier: 0.7,
    passiveDesc: 'Packet Loss: 15% chance to dodge attacks.',
    activeDesc: 'Jitter: CD 4. Disrupt target next turn logic.',
    cooldownMax: 4,
    truth: 'The ghost in the machine is real.',
  },
  [UnitType.WARDEN]: {
    type: UnitType.WARDEN,
    name: 'WARDEN',
    role: 'Controller',
    description: 'Slow, high integrity. Locks enemy movement.',
    special: 'Gridlock: Target cannot Move for 2 rounds.',
    hp: 1100,
    maxHp: 1100,
    speed: 3,
    focus: 10,
    dmgMultiplier: 0.9,
    passiveDesc: 'Heavyweight: Impossible to move via enemy effects.',
    activeDesc: 'Gridlock: Once per game. Lock target in current range.',
    cooldownMax: -1,
    truth: 'Nobody leaves until I say so.',
  },
  [UnitType.SINGULARITY]: {
    type: UnitType.SINGULARITY,
    name: 'SINGULARITY',
    role: 'Boss',
    description: 'Lowest HP but single hit is often lethal.',
    special: 'Collapse: Deal lethal damage to all range zones.',
    hp: 600,
    maxHp: 600,
    speed: 1,
    focus: 50,
    dmgMultiplier: 2.5,
    passiveDesc: 'Event Horizon: Reflects 10% damage back.',
    activeDesc: 'Collapse: Once per game. Unavoidable True Damage burst.',
    cooldownMax: -1,
    truth: 'The end is not a choice.',
  },
  [UnitType.RAVEN]: {
    type: UnitType.RAVEN,
    name: 'RAVEN',
    role: 'Intel',
    description: 'Sees the future. Precognitive tactical unit.',
    special: 'Precog: View and override opponent actions.',
    hp: 850,
    maxHp: 850,
    speed: 6,
    focus: 0,
    dmgMultiplier: 0.9,
    passiveDesc: 'Insight: Sees enemy Class and current HP.',
    activeDesc: 'Precog: Once per game. View and change opponent actions.',
    cooldownMax: -1,
    truth: 'Knowledge is the only real weapon.',
  }
};
